import json
from typing import List
from engine.contracts import ProcessingSession, ProcessingNode
from engine.repository import Repository

class NotebookExporter:
    def __init__(self, repository: Repository):
        self.repository = repository

    async def export(self, session_id: str) -> bytes:
        session = await self.repository.get_session(session_id)
        if not session:
            raise ValueError(f"Session {session_id} not found")

        dataset_name = session.input_metadata.get("dataset_name", "Unknown")
        dataset_path = session.input_metadata.get("dataset_path", "")

        nodes = await self.repository.list_nodes(session_id)
        # Sort nodes by creation time to maintain sequence
        sorted_nodes = sorted(nodes, key=lambda x: x.created_at)

        cells = []
        
        # Initial cell to load dataset
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                f"# Exploration Session: {dataset_name}\n",
                f"Generated by Explorex on {session.created_at}\n\n",
                "## Dataset Setup"
            ]
        })
        
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "import plotly.express as px\n",
                "import plotly.graph_objects as go\n\n",
                f"df = pd.read_csv('{dataset_path}')\n",
                "df.head()"
            ]
        })

        for node in sorted_nodes:
            if node.status != "completed":
                continue

            # Extract fields from output if available
            interpretation = ""
            audit_summary = ""
            reviewed_code = ""
            
            if node.output:
                interpretation = node.output.get("interpretation", "")
                audit_summary = node.output.get("audit_summary", "")
                reviewed_code = node.output.get("reviewed_code", "")

            # Markdown cell with trigger and audit summary
            markdown_source = [
                f"### Analysis: {node.trigger_input}\n",
                f"**Audit Summary:** {audit_summary or 'No summary available.'}\n"
            ]
            
            if interpretation:
                markdown_source.append(f"\n**Interpretation:**\n{interpretation}")

            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": markdown_source
            })

            # Code cell with reviewed code
            if reviewed_code:
                cells.append({
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {},
                    "outputs": [],
                    "source": [reviewed_code]
                })

        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "codemirror_mode": {
                        "name": "ipython",
                        "version": 3
                    },
                    "file_extension": ".py",
                    "mimetype": "text/x-python",
                    "name": "python",
                    "nbconvert_exporter": "python",
                    "pygments_lexer": "ipython3",
                    "version": "3.10.0"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 5
        }

        return json.dumps(notebook, indent=2).encode('utf-8')
